[package]
name = "sunrs-tray"
version = "0.2.0"
authors = ["Tim Deve <timdeve@users.noreply.github.com>"]
edition = "2018"

[dependencies]
sunrs = { git = "https://github.com/TimDeve/sunrs.git", tag = "v0.2.2" }
systray = "0.4.0"
