[package]
name = "sunrs-tray"
version = "0.1.0"
authors = ["Tim Deve <timdeve@users.noreply.github.com>"]
edition = "2018"

[dependencies]
sunrs = { git = "https://github.com/TimDeve/sunrs.git", rev = "6c99aa6" }
systray = "0.4.0"
